site_name: pgEdge Documentation

extra_css:
  - stylesheets/extra.css

extra_javascript:
  # Pulled from control-plane repo for install page
  - /control-plane/scripts/generate-stack.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - multirepo:
      cleanup: true
      keep_docs_dir: false
  - macros:
      j2_variable_start_string: "<<"
      j2_variable_end_string: ">>"
      j2_comment_start_string: "<#"
      j2_comment_end_string: "#>"
  - redoc-tag
  - gh-admonitions

theme: 
  name: material
  custom_dir: overrides

  logo_dark_mode: 'img/logo-dark.png'
  logo_light_mode: 'img/logo-light.png'

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.prune
    - navigation.top
    - toc.follow
    - content.code.copy

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra:
  generator: false
  # These values are required for pgedge-helm documentation templating
  # https://github.com/pgEdge/pgedge-helm/blob/main/mkdocs.yml#L52
  cnpg_manifest_url: https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.27/releases/cnpg-1.27.1.yaml
  certmanager_manifest_url: https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.yaml
  control_plane_version: v0.5.0

copyright: Copyright &copy; 2023 - 2025 pgEdge, Inc
repo_url: https://github.com/pgEdge

nav:
  - Welcome: index.md

  - pgEdge Enterprise Postgres:
    - Enterprise Edition: enterprise/index.md
    - Enterprise Linux 9 & 10: 
      - Enterprise Linux Version Support: enterprise/el/index.md
      - Getting Started - Configuring the Repository: enterprise/el/configure-repo.md
      - Installing Postgres: enterprise/el/installing.md
      - Installing Supporting Components: enterprise/el/components.md
      - Migrating to pgEdge Enterprise Postgres: enterprise/el/migrating.md
      - Upgrading Spock: enterprise/el/upgrading-spock.md
      - Creating an Offline Repo: enterprise/el/offline.md
    - Debian 11, 12, and 13 & Ubuntu 22.04 LTS and 24.04 LTS: 
      - Debian & Ubuntu Version Support: enterprise/debian/index.md
      - Getting Started - Configuring the Repository: enterprise/debian/configure-repo.md
      - Installing Postgres: enterprise/debian/installing.md
      - Installing Supporting Components: enterprise/debian/components.md
      - Migrating to pgEdge Enterprise Postgres: enterprise/debian/migrating.md
      - Upgrading Spock: enterprise/debian/upgrading-spock.md
      - Creating an Offline Repo: enterprise/debian/offline.md
    - Troubleshooting: enterprise/troubleshooting.md

  - pgEdge Distributed Postgres:
    - CLI Overview: platform/index.md
    - Prerequisites - Preparing your System:
      - Supported Operating Systems: platform/prerequisites/platforms.md
      - Preparing your System for the CLI: platform/prerequisites/index.md
      - pgEdge Architecture Models: platform/prerequisites/architecture.md
      - Planning for Active-Active Replication: platform/prerequisites/configuring.md
    - Installing pgEdge Distributed Postgres VM Edition:
      - Overview: platform/installing_pgedge/index.md
      - Tutorial - Manually Deploying a Cluster: platform/installing_pgedge/manual.md
      - Tutorial - Deploying a Cluster with a Configuration Files: platform/installing_pgedge/cluster_deploy.md
      - Creating, Managing, and Deploying with a Configuration Files: platform/installing_pgedge/json.md
      - Upgrading your CLI Installation: platform/installing_pgedge/upgrade_cli.md
      - Upgrading your Spock Installation: platform/installing_pgedge/upgrade_spock.md
      - Creating an Offline Repository for pgEdge Distributed Postgres: platform/installing_pgedge/offline_repo.md
    - Adding or Removing Cluster Nodes:
      - Using Spock to Synchronize a New Node: platform/modify/spock_sync.md
      - Adding a Node to your Cluster with the CLI: platform/modify/add_node.md
      - Removing a Node from your Cluster: platform/modify/remove_node.md
    - Managing a Cluster:
      - Setting Parameter Values: platform/managing/guc_values.md
      - Using Automatic DDL Replication: platform/managing/autoddl.md
      - Managing Replication Exceptions: platform/managing/exception.md
      - Managing Supported Extensions: platform/managing/supported_extensions.md
      - Configuring Backups with pgBackRest: platform/managing/pgbackrest.md
      - Creating Custom Filters: platform/managing/filtering.md
    - Monitoring Cluster Information: platform/monitoring/find_info.md
    - ACE (the Active Consistency Engine):
      - Managing Data Consistency with ACE: platform/ace/index.md
      - Installing ACE: platform/ace/installing_ace.md
      - Enhancing ACE Performance with Merkle Trees: platform/ace/merkle.md
      - Using ACE Functions: platform/ace/ace_functions.md
      - ACE API Endpoints: platform/ace/ace_api.md
      - Scheduling ACE Operations and Repairs: platform/ace/schedule_ace.md
    - CLI Reference:
      - Using the CLI: platform/pgedge_commands/index.md
      - ace Commands: 
        - ACE commands: platform/pgedge_commands/ace/index.md
        - ace-mtree: platform/pgedge_commands/doc/ace-mtree.md
        - ace-repset-diff: platform/pgedge_commands/doc/ace-repset-diff.md
        - ace-schema-diff: platform/pgedge_commands/doc/ace-schema-diff.md
        - ace-spock-diff: platform/pgedge_commands/doc/ace-spock-diff.md
        - ace-spock-exception-update: platform/pgedge_commands/doc/ace-spock-exception-update.md
        - ace-start: platform/pgedge_commands/doc/ace-start.md
        - ace-table-diff: platform/pgedge_commands/doc/ace-table-diff.md
        - ace-table-repair: platform/pgedge_commands/doc/ace-table-repair.md
        - ace-table-rerun: platform/pgedge_commands/doc/ace-table-rerun.md
      - db Commands: 
        - db Commands: platform/pgedge_commands/db/index.md
        - db-create: platform/pgedge_commands/doc/db-create.md
        - db-guc-set: platform/pgedge_commands/doc/db-guc-set.md
        - db-guc-show: platform/pgedge_commands/doc/db-guc-show.md
        - db-set-readonly: platform/pgedge_commands/doc/db-set-readonly.md
        - db-test-io: platform/pgedge_commands/doc/db-test-io.md
      - cluster Commands:
        - cluster Commands: platform/pgedge_commands/cluster/index.md
        - cluster-add-db: platform/pgedge_commands/doc/cluster-add-db.md
        - cluster-add-node: platform/pgedge_commands/doc/cluster-add-node.md
        - cluster-app-concurrent-index: platform/pgedge_commands/doc/cluster-app-concurrent-index.md
        - cluster-app-install: platform/pgedge_commands/doc/cluster-app-install.md
        - cluster-app-remove: platform/pgedge_commands/doc/cluster-app-remove.md
        - cluster-command: platform/pgedge_commands/doc/cluster-command.md
        - cluster-init: platform/pgedge_commands/doc/cluster-init.md
        - cluster-json-create: platform/pgedge_commands/doc/cluster-json-create.md
        - cluster-json-template: platform/pgedge_commands/doc/cluster-json-template.md
        - cluster-json-validate: platform/pgedge_commands/doc/cluster-json-validate.md
        - cluster-list-nodes: platform/pgedge_commands/doc/cluster-list-nodes.md
        - cluster-remove-node: platform/pgedge_commands/doc/cluster-remove-node.md
        - cluster-remove: platform/pgedge_commands/doc/cluster-remove.md
        - cluster-replication-begin: platform/pgedge_commands/doc/cluster-replication-begin.md
        - cluster-replication-check: platform/pgedge_commands/doc/cluster-replication-check.md
        - cluster-ssh: platform/pgedge_commands/doc/cluster-ssh.md
      - localhost Commands: 
        - localhost Commands: platform/pgedge_commands/localhost/index.md
        - localhost-cluster-create: platform/pgedge_commands/doc/localhost-cluster-create.md
        - localhost-cluster-deploy: platform/pgedge_commands/doc/localhost-cluster-destroy.md
      - service Commands: 
        - service Commands: platform/pgedge_commands/service/index.md
        - service-config: platform/pgedge_commands/doc/service-config.md
        - service-disable: platform/pgedge_commands/doc/service-disable.md
        - service-enable: platform/pgedge_commands/doc/service-enable.md
        - service-init: platform/pgedge_commands/doc/service-init.md
        - service-reload: platform/pgedge_commands/doc/service-reload.md
        - service-restart: platform/pgedge_commands/doc/service-restart.md
        - service-start: platform/pgedge_commands/doc/service-start.md
        - service-status: platform/pgedge_commands/doc/service-status.md
        - service-stop: platform/pgedge_commands/doc/service-stop.md
      - The setup Command: 
        - The setup Command: platform/pgedge_commands/setup/index.md
        - setup: platform/pgedge_commands/doc/setup.md
      - spock Commands: 
        - spock Commands: platform/pgedge_commands/spock/index.md
        - spock-health-check: platform/pgedge_commands/doc/spock-health-check.md
        - spock-metrics-check: platform/pgedge_commands/doc/spock-metrics-check.md
        - spock-node-add-interface: platform/pgedge_commands/doc/spock-node-add-interface.md
        - spock-node-alter-location: platform/pgedge_commands/doc/spock-node-alter-location.md
        - spock-node-create: platform/pgedge_commands/doc/spock-node-create.md
        - spock-node-drop-interface: platform/pgedge_commands/doc/spock-node-drop-interface.md
        - spock-node-drop: platform/pgedge_commands/doc/spock-node-drop.md
        - spock-node-list: platform/pgedge_commands/doc/spock-node-list.md
        - spock-replicate-ddl: platform/pgedge_commands/doc/spock-replicate-ddl.md
        - spock-repset-add-partition: platform/pgedge_commands/doc/spock-repset-add-partition.md
        - spock-repset-add-table: platform/pgedge_commands/doc/spock-repset-add-table.md
        - spock-repset-alter: platform/pgedge_commands/doc/spock-repset-alter.md
        - spock-repset-create: platform/pgedge_commands/doc/spock-repset-create.md
        - spock-repset-drop: platform/pgedge_commands/doc/spock-repset-drop.md
        - spock-repset-list-tables: platform/pgedge_commands/doc/spock-repset-list-tables.md
        - spock-repset-remove-partition: platform/pgedge_commands/doc/spock-repset-remove-partition.md
        - spock-repset-remove-table: platform/pgedge_commands/doc/spock-repset-remove-table.md
        - spock-sequence-convert: platform/pgedge_commands/doc/spock-sequence-convert.md
        - spock-set-readonly: platform/pgedge_commands/doc/spock-set-readonly.md
        - spock-sub-add-repset: platform/pgedge_commands/doc/spock-sub-add-repset.md
        - spock-sub-alter-interface: platform/pgedge_commands/doc/spock-sub-alter-interface.md
        - spock-sub-create: platform/pgedge_commands/doc/spock-sub-create.md
        - spock-sub-disable: platform/pgedge_commands/doc/spock-sub-disable.md
        - spock-sub-drop: platform/pgedge_commands/doc/spock-sub-drop.md
        - spock-sub-enable: platform/pgedge_commands/doc/spock-sub-enable.md
        - spock-sub-remove-repset: platform/pgedge_commands/doc/spock-sub-remove-repset.md
        - spock-sub-resync-table: platform/pgedge_commands/doc/spock-sub-resync-table.md
        - spock-sub-show-status: platform/pgedge_commands/doc/spock-sub-show-status.md
        - spock-sub-show-table: platform/pgedge_commands/doc/spock-sub-show-table.md
        - spock-sub-wait-for-sync: platform/pgedge_commands/doc/spock-sub-wait-for-sync.md
        - spock-table-wait-for-sync: platform/pgedge_commands/doc/spock-table-wait-for-sync.md
      - update manager Commands: 
        - um Commands: platform/pgedge_commands/um/index.md
        - um-clean.md: platform/pgedge_commands/doc/um-clean.md
        - um-download.md: platform/pgedge_commands/doc/um-download.md
        - um-install.md: platform/pgedge_commands/doc/um-install.md
        - um-list.md: platform/pgedge_commands/doc/um-list.md
        - um-remove.md: platform/pgedge_commands/doc/um-remove.md
        - um-update.md: platform/pgedge_commands/doc/um-update.md
        - um-upgrade.md: platform/pgedge_commands/doc/um-upgrade.md
        - um-verify-metadata.md: platform/pgedge_commands/doc/um-verify-metadata.md
    - pgEdge Distributed Postgres VM Edition Release Notes: platform/pgedge_rel_notes.md
    - Troubleshooting: platform/troubleshooting.md

  - pgEdge Cloud:
    - Cloud Edition: cloud/index.md
    - Getting Started: 
      - Enterprise Edition: cloud/getting_started/ee_getting_started.md
      - Developer Edition: cloud/getting_started/de_getting_started.md
    - Prerequisites: 
      - Adding an SSH Key: cloud/prerequisites/ssh_key.md
      - Linking and Managing your Cloud Provider Accounts:
        - Managing Cloud Provider Accounts: cloud/prerequisites/cloud_accounts/index.md
        - Linking an AWS Account: cloud/prerequisites/cloud_accounts/link_to_AWS.md
        - Linking an Azure Account: cloud/prerequisites/cloud_accounts/link_to_Azure.md
        - Linking a Google Account: cloud/prerequisites/cloud_accounts/link_to_Google.md
    - Cluster Management:
      - Reviewing your Cloud Clusters: cloud/cluster/index.md
      - Creating a Cluster: cloud/cluster/create_cluster.md
      - Managing a Cluster: cloud/cluster/manage_cluster.md
      - Defining a Cluster's Backup Store: cloud/cluster/backup_store.md
      - Managing Firewall Rules: cloud/cluster/firewall.md
      - Managing VPC Associations: cloud/cluster/vpc_assoc.md
    - Database Management:
      - Reviewing your Databases: cloud/database/index.md
      - Creating a Database: cloud/database/create_db.md
      - Managing a Database: cloud/database/manage_db.md
    - Modifying a Database or a Cluster: 
      - Using the Actions Menu: cloud/mod_cluster/actions.md
      - Adding a Database or Cluster Node: cloud/mod_cluster/add.md
      - Dropping a Database, Node, or Cluster: cloud/mod_cluster/drop.md
      - Modifying a Database, Node, or Cluster: cloud/mod_cluster/modify.md
    - Database Administration: 
      - Creating and Managing Tables: cloud/database_admin/table_mgmt.md
      - Using Integrations: cloud/database_admin/integrations.md
      - Reviewing Database Metrics: cloud/database_admin/metrics.md
      - Viewing Log Files: cloud/database_admin/logs.md
      - Reviewing Backup Details: cloud/database_admin/backup_details.md
      - Using Postgres Extensions: cloud/database_admin/extensions.md
    - Connecting to a Database: 
      - Connecting to your Database or Cluster: cloud/connecting/index.md
      - Connecting with SSH: cloud/connecting/ssh.md
      - Connecting with psql: cloud/connecting/psql.md
      - Connecting with pgAdmin: cloud/connecting/pgadmin.md
      - Connecting a Custom Client: cloud/connecting/custom_client.md
      - Connecting over HTTPS: cloud/connecting/https.md
      - Best Practices for Managing Connections: cloud/connecting/best_practices.md
    - Managing Database Backups:
      - Reviewing Backup Details: cloud/backup/backups.md
      - Backing up your Database: cloud/backup/backup_providers.md
      - Restoring from Backup: cloud/backup/restore.md
    - Reviewing Console Tasks: cloud/tasks.md
    - Migrating to pgEdge Distributed Postgres (Cloud Edition):
      - Overview - Using a Backup to Migrate into a Distributed Database: cloud/migration/index.md
      - Taking a Backup: cloud/migration/backup.md
      - Restoring from Backup:  cloud/migration/restore.md
    - Settings: cloud/settings.md
    - Team Resources: cloud/teams.md
    - Troubleshooting: cloud/troubleshooting.md
    - pgEdge Distributed Postgres (Cloud Edition) Release Notes: cloud/cl_release_notes.md  

  # Pinned to latest release - this should be updated when a new release is cut
  # Macro variables under extra also need to be updated, if changed
  - pgEdge Containers: '!import https://github.com/pgEdge/pgedge-helm.git?branch=v0.0.4'
  - ACE: '!import https://github.com/pgEdge/ace.git?branch=main'
  - lolor: '!import https://github.com/pgEdge/lolor.git?branch=main'
  - Snowflake: '!import https://github.com/pgEdge/snowflake.git?branch=main'
  - Spock v5: '!import https://github.com/pgEdge/spock.git?branch=v5_STABLE'
  - Control Plane: '!import https://github.com/pgEdge/control-plane.git?branch=v0.5.0'



  
